"""add_lifecycle_columns

Revision ID: cb434851e1ea
Revises: 08f5798b193f
Create Date: 2026-07-07 16:02:53.207459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb434851e1ea'
down_revision: Union[str, None] = '08f5798b193f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('upload_status', sa.String(), server_default='completed', nullable=False))
    op.add_column('documents', sa.Column('parsing_status', sa.String(), server_default='pending', nullable=False))
    op.add_column('documents', sa.Column('embedding_status', sa.String(), server_default='pending', nullable=False))
    op.add_column('documents', sa.Column('summary_status', sa.String(), server_default='pending', nullable=False))
    op.add_column('documents', sa.Column('flashcard_status', sa.String(), server_default='pending', nullable=False))
    op.add_column('documents', sa.Column('quiz_status', sa.String(), server_default='pending', nullable=False))
    op.add_column('documents', sa.Column('graph_status', sa.String(), server_default='pending', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'graph_status')
    op.drop_column('documents', 'quiz_status')
    op.drop_column('documents', 'flashcard_status')
    op.drop_column('documents', 'summary_status')
    op.drop_column('documents', 'embedding_status')
    op.drop_column('documents', 'parsing_status')
    op.drop_column('documents', 'upload_status')
    # ### end Alembic commands ###
